## InfluxDB

- name: Install libselinux-python
  yum: name=libselinux-python state=present
  
- name: Create a influxdb.repo file 
  file: path=/etc/yum.repos.d/influxdb.repo state=touch

- name: Update /etc/yum.repos.d/influxdb.repo file
  blockinfile:
    dest: /etc/yum.repos.d/influxdb.repo
    content: |
      
      [influxdb]
      name = InfluxDB Repository - RHEL \$releasever
      baseurl = https://repos.influxdata.com/rhel/\$releasever/\$basearch/stable
      enabled = 1
      gpgcheck = 1
      gpgkey = https://repos.influxdata.com/influxdb.key

- name: Install influxdb
  yum: name=influxdb state=present

- name: Enable and start influxdb   
  shell: "{{item}}"
  with_items:
    - /bin/systemctl daemon-reload
    - /bin/systemctl enable influxdb.service
    - /bin/systemctl start influxdb.service

- name: Create testdb in influxDB
  shell: curl -i -XPOST http://localhost:8086/query --data-urlencode "q=CREATE DATABASE {{test_metrics_db_name}}"
  when: test_metrics_db_name is defined
  tags:
    - create-testdb
