## InfluxDB main task playbook

- include: centos7.yml
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version > '6'

- include: ubuntu16.yml
  when: ansible_distribution == "Ubuntu" and ansible_distribution_release == 'xenial'
        
- name: Enable and start influxdb   
  shell: "{{item}}"
  with_items:
    - /bin/systemctl daemon-reload
    - /bin/systemctl enable influxdb.service
    - /bin/systemctl start influxdb.service
  tags:
    - startup
    
- name: Create testdb in influxDB
  shell: curl -i -XPOST http://localhost:8086/query --data-urlencode "q=CREATE DATABASE {{test_metrics_db_name}}"
  when: test_metrics_db_name is defined
  tags:
    - create-testdb
