---

- hosts: server
  become: true
  vars:
    grafana_url: https://s3-us-west-2.amazonaws.com/grafana-releases/release/grafana-4.3.1-1.x86_64.rpm
    metrics_db: metrics
    
  roles:
    - influxDB
    - grafana
