---

## 
## Assumes installation of Grafana & InfluxDB and the same host 
##

## 
## Check for the newest grafana at: https://grafana.com/grafana/download
##

- hosts: influxdb-grafana-host
  become: true
  vars:
    grafana_url: https://s3-us-west-2.amazonaws.com/grafana-releases/release/grafana-4.4.3-1.x86_64.rpm
    test_metrics_db_name: test_metrics

  roles:
    - influxDB
    - grafana


##
## Playbook for nginx servers, assumes InfluxDB & Grafana installed  
##

- hosts: nginx-servers
  become: true
  vars:
    influxdb_host: influxdb-grafana-host
    server_group_name: web-cluster
    nginx_metrics_db_name: nginx_metrics

  roles:
    - telegraf-nginx

    
##
## Playbook for apache servers, assumes InfluxDB & Grafana installed  
##

- hosts: apache-servers
  become: true
  vars:
    influxdb_host: influxdb-grafana-host
    server_group_name: web-cluster
    apache_metrics_db_name: apache_metrics

  roles:
    - telegraf-apache
