## Telegraf                                                                                                     

- name: Install libselinux-python
  yum: name=libselinux-python state=present

- name: Create a influxdb.repo file
  file: path=/etc/yum.repos.d/influxdb.repo state=touch

- name: Update /etc/yum.repos.d/influxdb.repo file
  blockinfile:
    dest: /etc/yum.repos.d/influxdb.repo
    content: |
      
      [influxdb]
      name = InfluxDB Repository - RHEL \$releasever
      baseurl = https://repos.influxdata.com/rhel/\$releasever/\$basearch/stable
      enabled = 1
      gpgcheck = 1
      gpgkey = https://repos.influxdata.com/influxdb.key  

- name: Install the telegraf rpm from a remote repo
  yum:
    name: telegraf
    state: present

- name: Fetch config
  template: src=apache_telegraf.conf.j2 dest=/etc/telegraf/telegraf.conf
  notify:
    - restart telegraf
  tags:
    - config

- name: Enabled telegraf service and start it
  shell: "{{item}}"
  with_items:
    - systemctl enable telegraf.service
    - systemctl start telegraf.service
  tags:
    - startup

- name: Create testdb in influxDB
  shell: curl -i -XPOST http://localhost:8086/query --data-urlencode "q=CREATE DATABASE {{apache_metrics_db_name}}"
  delegate_to: "{{influxdb_host}}"
  tags:
    - create-nginx-metrics
